# Generated by Django 5.0.4 on 2024-04-28 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiorecording',
            name='name',
        ),
        migrations.AddField(
            model_name='audiorecording',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
